### ISSUE TITLE
Understanding of areas property in Grid component

### ISSUE THREAD

**Issue by FabienSalles** [grommet/grommet#2902]
Hi,

I didn't know how to use grid layout in CSS before try to learn to use them with Grommet.
I tried to use grid component but it wasn't obvious for me to create what i wanted.

So I read articles, I understood what areas coordinates do in your code but I didn't find the similitude between your coordinates and coordinates in CSS grid.

Your coordinates seems to only have the purpose to create grid-template-areas and seems to differ of grid-column/row coordinates in CSS. So why don't use directly a parameter that represent grid-template-areas like in CSS instead of create additional logic with specific coordinates ?

For my point of you (I'm not a frontend developer), It could be easier to use your Grid component with more similitude with CSS Grid layout. 

Could you explain to me your choice about this ?
Thanks.

**Comment by oorestisime** [comment]
Hello,

Can you please share some information on how you wanted the Grid to behave? Seems like you wanted to replicate `grid-template-columns` and this is available through https://v2.grommet.io/grid#columns
For example `<Grid columns="200px" />` should create something like 
```
grid-template-columns: auto-fill, minmax(200px, 1fr);
```
Maybe we need to update the docs to better reflect the available possibilities.

**Comment by FabienSalles** [comment]
I created this Grid layout : 
```javascript
<Grommet full>
    <Grid
      fill
      rows={["xxsmall", "flex", "xxsmall"]}
      columns={["auto", "flex"]}
      gap="xsmall"
      areas={[
        { name: "header", start: [0, 0], end: [1, 0] },
        { name: "nav", start: [0, 1], end: [0, 1] },
        { name: "main", start: [1, 1], end: [1, 1] },
        { name: "footer", start: [0, 2], end: [1, 2] }
      ]}
    >
      <Box gridArea="header" background="#f89325">
        Header
      </Box>
      <Box gridArea="nav" background="#e4281b">
        nav
      </Box>
      <Box gridArea="main" background="#25f864">
        Contents
      </Box>
      <Box gridArea="footer" background="#3b64d4">
        footer
      </Box>
    </Grid>
  </Grommet>
```

This generate a css like this : 
```css
.grid {
  display: grid;
  width: 100vw;
  height: 100vh;
  grid-template-areas: "header header" "nav main" "footer footer";
  grid-template-columns: auto 1fr;
  grid-gap: 6px 6px;
  grid-template-rows: 48px 1fr 48px;
}

.header {
  grid-area: header;
}

.nav {
  grid-area: nav;
}

.main {
  grid-area: main;
}

.footer {
  grid-area: footer;
}
```

I understood how areas create the `grid-template-areas` property but i had difficulties at the beginning to specify the correct coordinates with Grommet. So I tried to understand if these coordinates had an other signification and I replicated a CSS grid layout with these coordinates like these : 

```css
.grid {
  display: grid;
  width: 100vw;
  height: 100vh;
  grid-template-columns: auto 1fr;
  grid-gap: 6px 6px;
  grid-template-rows: 48px 1fr 48px;
}

.header {
  grid-column-start: 0;
  grid-row-start: 0;
  grid-column-end: 1;
  grid-row-end: 0;
}

.nav {
  grid-column-start: 0;
  grid-row-start: 1;
  grid-column-end: 0;
  grid-row-end: 1;
}

.main {
  grid-column-start: 1;
  grid-row-start: 1;
  grid-column-end: 1;
  grid-row-end: 1;
}

.footer {
  grid-column-start: 0;
  grid-row-start: 2;
  grid-column-end: 1;
  grid-row-end: 2;
}
``` 

And I found that these coordinates wasn't valid css grid coordinates. To works correctly we have to specify this instead : 

```css
.header {
  grid-column-start: 1;
  grid-row-start: 1;
  grid-column-end: 3;
  grid-row-end: 1;
}

.nav {
  grid-column-start: 1;
  grid-row-start: 2;
  grid-column-end: 1;
  grid-row-end: 2;
}

.main {
  grid-column-start: 2;
  grid-row-start: 2;
  grid-column-end: 2;
  grid-row-end: 2;
}

.footer {
  grid-column-start: 1;
  grid-row-start: 3;
  grid-column-end: 3;
  grid-row-end: 3;
}
```

If you want I created 3 codesanbox : 
* one with grommet : https://codesandbox.io/s/4qox3xky57
* a second with css grid-template-areas : https://codesandbox.io/s/5x50n33rln
* and a third with css grid-column/grid-row : https://codesandbox.io/s/6x98x11wjk

Honestly, I don't fully understand what I did with css coordinates but this works. 
The grid-template-areas is simpler for my point of view so my question was about the purpose of your coordinates ?
May be you use this solution to workaround the multiples double-quotes but if it is the only reason I would prefer to have an areas property like this : 
~~~
<Grommet full>
    <Grid
      ...
      areas={[
         "header header",
         "nav main",
         "footer footer"
      ]}
    >
      ...
    </Grid>
  </Grommet>
~~~
