### ISSUE TITLE
Apply global font-family

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#6995]
I find this code snippet for change the global font-family. However, there is only one font.
```javascript
const customTheme = deepMerge(grommet, {
  paragraph: {
    global: {
      family: 'Comic Sans MS',
    },
  },
});
```
But we need to apply a lot of fonts to the font-family:
```css
body {
    font-family: -apple-system, BlinkMacSystemFont, "PingFang SC","Helvetica Neue",STHeiti,"Microsoft Yahei",Tahoma,Simsun,sans-serif;
}
```
How could we do?
